old_sound_rabbit_mq:
    connections:
        default:
            host: '172.17.0.4'
            user: 'user'
            password: 'password'
            vhost: 'n2g'
    producers:
        publish:
            connection: default
            exchange_options:
                name: cand_yk06
                type: topic
    consumers:
        consume:
            connection:       default
            exchange_options: {name: 'cand_yk06', type: topic}
            queue_options:    {name: 'cand_yk06_results'}
            callback:         message_service
            idle_timeout:           15